// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvrIK16RySCeNgQb_NEJl95XBytgxyFnQ',
    appId: '1:817463616147:web:67597718f9b3c125bd2366',
    messagingSenderId: '817463616147',
    projectId: 'resonance-chatroom',
    authDomain: 'resonance-chatroom.firebaseapp.com',
    storageBucket: 'resonance-chatroom.appspot.com',
    measurementId: 'G-4N94Q90X3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPjZDx9I1ylfdxksx_n2mp57mNaDSND3c',
    appId: '1:817463616147:android:d11af1b7b51fd672bd2366',
    messagingSenderId: '817463616147',
    projectId: 'resonance-chatroom',
    storageBucket: 'resonance-chatroom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NjIE1nkpnb9LC8RBTVFRNNBPsMIDvAI',
    appId: '1:817463616147:ios:9cdca607abb2fb79bd2366',
    messagingSenderId: '817463616147',
    projectId: 'resonance-chatroom',
    storageBucket: 'resonance-chatroom.appspot.com',
    androidClientId: '817463616147-15ahgnhbbh1049qs02t2e0rcuhvf338n.apps.googleusercontent.com',
    iosClientId: '817463616147-4n6214dmcgmlq044g7osp3o05b6egh53.apps.googleusercontent.com',
    iosBundleId: 'com.ntpu.resonanceChatroom',
  );
}
